ETAB
2734	01.09.2009	PROD	HLIQ  HWEF    BHPT 10 
2734	13.09.2012	INJE	HWAT  HWEF    BHPT 500 
--********************--
2443	01.05.2013	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2770	01.09.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
120RTM	01.08.1989	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2733	01.10.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2740	01.07.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2244	01.04.2010	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2263	01.06.2009	PROD	HLIQ  HWEF    BHPT 10 
2263	01.12.2012	INJE	HWAT  HWEF    BHPT 500 
--********************--
2240	01.01.2010	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2241	01.07.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2264	01.03.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2265	01.03.2009	PROD	HLIQ  HWEF    BHPT 10 
2265	12.05.2011	INJE	HWAT  HWEF    BHPT 500 
--********************--
2604	01.03.2010	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2605	01.01.2010	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2466	01.01.2002	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2607	01.12.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2446	01.08.2000	PROD	HLIQ  HWEF    BHPT 10 
2446	12.05.2010	INJE	HWAT  HWEF    BHPT 500 
--********************--
2602	01.06.2010	PROD	HLIQ  HWEF    BHPT 10 
2602	08.09.2012	INJE	HWAT  HWEF    BHPT 500 
--********************--
2603	01.08.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2468	01.07.2003	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2726	01.11.2009	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2518	01.06.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2516	01.07.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2517	01.04.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
ENDE
